name: cumulus
recipe: wordpress
config:
  webroot: wp

services:
  appserver:
    run:
      - composer install
      - ./scripts/setup-wordpress.sh

  # TODO cljs service

tooling:
  install:
    cmd: ./scripts/setup-wordpress.sh
    description: Install and configure WordPress
    service: appserver